# Generated by Django 3.2.9 on 2021-12-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "path",
                    models.CharField(max_length=64, unique=True, verbose_name="文件Path"),
                ),
                ("response", models.JSONField(default=dict, verbose_name="相应参数")),
                ("operator", models.CharField(max_length=24, verbose_name="操作人")),
                (
                    "upload_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
            ],
            options={
                "db_table": "cos_log",
            },
        ),
    ]
