# Generated by Django 4.0 on 2021-12-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uploadlog",
            options={"verbose_name": "上传日志", "verbose_name_plural": "上传日志"},
        ),
    ]
