from constents.conf import *  # noqa
from constents.doc import *  # noqa
from constents.repo import *  # noqa

DEFAULT_GETTEXT_LAY_COUNT = 1
VERIFY_CODE_LENGTH = 6
USERNAME_MIN_LENGTH = 4
BUTTON_MAX_LENGTH = 6
SMALL_SHORT_CHAR_LENGTH = 12
SHORT_CHAR_LENGTH = 24
MEDIUM_CHAR_LENGTH = 64
PHONE_NUMBER_CHAR_LENGTH = 11
CHINA_PHONE_NUMBER_CHAR_LENGTH = 14
MAX_CHAR_LENGTH = 255
