# Generated by Django 3.2.9 on 2021-12-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0003_alter_doc_index_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="doc_id",
            field=models.BigIntegerField(db_index=True, verbose_name="文档id"),
        ),
        migrations.AlterField(
            model_name="commentversion",
            name="doc_id",
            field=models.BigIntegerField(db_index=True, verbose_name="文档id"),
        ),
        migrations.AlterField(
            model_name="docversion",
            name="repo_id",
            field=models.BigIntegerField(db_index=True, verbose_name="仓库id"),
        ),
        migrations.AlterIndexTogether(
            name="comment",
            index_together={("creator", "is_deleted")},
        ),
        migrations.AlterIndexTogether(
            name="doc",
            index_together={("creator", "is_deleted"), ("repo_id", "creator")},
        ),
    ]
