# Generated by Django 3.2.9 on 2021-12-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0004_auto_20211208_1947"),
    ]

    operations = [
        migrations.AddField(
            model_name="doc",
            name="html",
            field=models.TextField(blank=True, null=True, verbose_name="渲染完成内容"),
        ),
        migrations.AddField(
            model_name="docversion",
            name="html",
            field=models.TextField(blank=True, null=True, verbose_name="渲染完成内容"),
        ),
    ]
