# Generated by Django 3.2.9 on 2021-12-11 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0005_auto_20211211_1315"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doc",
            name="html",
        ),
        migrations.RemoveField(
            model_name="docversion",
            name="html",
        ),
    ]
