# Generated by Django 3.2.9 on 2021-12-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0006_auto_20211211_1339"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="docversion",
            options={"verbose_name": "文档版本", "verbose_name_plural": "文档版本"},
        ),
        migrations.CreateModel(
            name="DocCollaborator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_id", models.BigIntegerField(verbose_name="文章ID")),
                ("uid", models.CharField(max_length=24, verbose_name="协作人ID")),
                (
                    "add_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
            ],
            options={
                "verbose_name": "协作成员",
                "verbose_name_plural": "协作成员",
                "db_table": "doc_collaborator",
                "unique_together": {("doc_id", "uid")},
            },
        ),
    ]
