# Generated by Django 4.0 on 2021-12-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0007_auto_20211211_1551"),
    ]

    operations = [
        migrations.CreateModel(
            name="PinDoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_id", models.BigIntegerField(verbose_name="文章ID")),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("pin_to", models.DateTimeField(verbose_name="置顶到期时间")),
                ("operator", models.CharField(max_length=24, verbose_name="操作人")),
                ("in_use", models.BooleanField(default=True, verbose_name="使用中")),
            ],
            options={
                "verbose_name": "置顶文章",
                "verbose_name_plural": "置顶文章",
                "db_table": "doc_pin",
                "ordering": ["-id"],
                "index_together": {("doc_id", "in_use")},
            },
        ),
    ]
