# Generated by Django 4.0 on 2021-12-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0008_pindoc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pindoc",
            name="in_use",
            field=models.BooleanField(db_index=True, default=True, verbose_name="使用中"),
        ),
    ]
