# Generated by Django 4.0 on 2021-12-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0009_alter_pindoc_in_use"),
    ]

    operations = [
        migrations.AddField(
            model_name="doc",
            name="update_by",
            field=models.CharField(
                blank=True, max_length=24, null=True, verbose_name="更新人"
            ),
        ),
        migrations.AddField(
            model_name="docversion",
            name="update_by",
            field=models.CharField(
                blank=True, max_length=24, null=True, verbose_name="更新人"
            ),
        ),
    ]
