# Generated by Django 4.0.1 on 2022-01-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0011_alter_doc_index_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="doc",
            name="pv",
            field=models.IntegerField(db_index=True, default=0, verbose_name="访问量"),
        ),
        migrations.AddField(
            model_name="docversion",
            name="pv",
            field=models.IntegerField(db_index=True, default=0, verbose_name="访问量"),
        ),
    ]
