# Generated by Django 4.0.4 on 2022-04-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0013_remove_doc_pv_remove_docversion_pv"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectDoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=24, verbose_name="用户ID")),
                ("doc_id", models.BigIntegerField(verbose_name="文章ID")),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "收藏文章",
                "verbose_name_plural": "收藏文章",
                "db_table": "doc_collect",
                "ordering": ["-id"],
                "unique_together": {("uid", "doc_id")},
            },
        ),
    ]
