fail_fast: true
default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: check-merge-conflict
#  - repo: https://github.com/pre-commit/mirrors-isort
#    rev: v5.9.3
#    hooks:
#    - id: isort
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
    - id: autopep8
      args: [-i, --global-config=.flake8, -v]
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    - id: flake8
