# Generated by Django 3.2.9 on 2021-11-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SMSLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=14, verbose_name="电话号码")),
                ("template_id", models.CharField(max_length=24, verbose_name="模板ID")),
                (
                    "template_params",
                    models.JSONField(blank=True, null=True, verbose_name="模板参数"),
                ),
                (
                    "send_status",
                    models.JSONField(blank=True, null=True, verbose_name="发送情况"),
                ),
                ("operator", models.CharField(max_length=24, verbose_name="处理人")),
                (
                    "send_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
                ),
            ],
            options={
                "db_table": "sms_log",
            },
        ),
    ]
