# Generated by Django 4.0 on 2021-12-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="smslog",
            options={"verbose_name": "短信", "verbose_name_plural": "短信"},
        ),
    ]
