# Generated by Django 4.0.1 on 2022-02-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0002_alter_smslog_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SMSLog",
        ),
    ]
