# Generated by Django 4.0 on 2021-12-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "vid",
                    models.CharField(
                        max_length=24,
                        primary_key=True,
                        serialize=False,
                        verbose_name="版本号",
                    ),
                ),
                ("content", models.TextField(verbose_name="日志内容")),
                ("release_at", models.DateField(verbose_name="发布时间")),
                ("is_current", models.BooleanField(verbose_name="当前版本")),
            ],
            options={
                "db_table": "version_log",
            },
        ),
    ]
