# Generated by Django 3.2.9 on 2021-12-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active_index",
            field=models.FloatField(default=0, verbose_name="活跃指数"),
        ),
    ]
