# Generated by Django 4.0 on 2022-01-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_active_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(db_index=True, max_length=11, verbose_name="联系电话"),
        ),
    ]
