# Generated by Django 4.0 on 2021-12-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_active_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=11, null=True, unique=True, verbose_name="联系电话"
            ),
        ),
    ]
