# Generated by Django 4.0.1 on 2022-01-22 14:22

from django.db import migrations, models
import modules.log.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operator", models.CharField(max_length=24, verbose_name="操作人")),
                ("model", models.CharField(max_length=24, verbose_name="模型")),
                ("function", models.CharField(max_length=64, verbose_name="方法")),
                ("result", models.BooleanField(default=True, verbose_name="结果")),
                (
                    "detail",
                    models.JSONField(
                        default=modules.log.models.get_default_detail,
                        verbose_name="详细信息",
                    ),
                ),
                ("ip", models.GenericIPAddressField(verbose_name="IP地址")),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "日志",
                "verbose_name_plural": "日志",
                "db_table": "log_log",
                "ordering": ["-id"],
                "index_together": {("operator", "function", "model")},
            },
        ),
    ]
