# Generated by Django 4.0.1 on 2022-01-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="operator",
            field=models.CharField(
                blank=True, max_length=24, null=True, verbose_name="操作人"
            ),
        ),
    ]
