# Generated by Django 4.0.2 on 2022-03-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0002_alter_log_operator"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocVisitLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_id", models.BigIntegerField(verbose_name="文章ID")),
                ("visitor", models.CharField(max_length=24, verbose_name="访问者ID")),
                (
                    "visit_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="访问时间"),
                ),
            ],
            options={
                "verbose_name": "访问日志",
                "verbose_name_plural": "访问日志",
                "db_table": "log_doc_visit",
                "index_together": {("doc_id", "visit_at")},
            },
        ),
    ]
