# Generated by Django 4.0.2 on 2022-03-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0003_docvisitlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docvisitlog",
            name="visitor",
            field=models.CharField(
                blank=True, max_length=24, null=True, verbose_name="访问者ID"
            ),
        ),
    ]
