# Generated by Django 4.0.2 on 2022-03-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0004_alter_docvisitlog_visitor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Log",
        ),
    ]
