# Generated by Django 4.0.2 on 2022-03-19 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0006_log"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Log",
        ),
    ]
