# Generated by Django 4.0.4 on 2022-04-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0007_delete_log"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="docvisitlog",
            index_together=set(),
        ),
        migrations.AddField(
            model_name="docvisitlog",
            name="ip",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="IP"
            ),
        ),
        migrations.AddField(
            model_name="docvisitlog",
            name="ua",
            field=models.TextField(blank=True, null=True, verbose_name="用户代理"),
        ),
        migrations.AlterIndexTogether(
            name="docvisitlog",
            index_together={("doc_id", "visitor", "ip")},
        ),
    ]
