name: Code Check

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:

        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [ 3.9 ]

        steps:
            -   uses: actions/checkout@v2
            -   name: Frontend - Install Packages
                run: |
                    cd frontend
                    yarn install
                    yarn global add eslint
            -   name: Frontend - Run ESLint
                run: |
                    cd frontend
                    eslint --ext .js,.vue
            -   name: Backend - Setup Python3.9
                uses: actions/setup-python@v2
                with:
                    python-version: 3.9
            -   name: Backend - Install Dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install pre-commit
            -   name: Backend - Run PreCommit
                run: |
                    pre-commit run -a
