name: Django CI

on:
    push:
        branches: [ master, develop ]
    pull_request:
        branches: [ master, develop ]

env:
    APP_CODE: iWiki
    APP_SECRET_KEY: iWiki
    BACKEND_HOST: 127.0.0.1
    FRONTEND_URL: http://127.0.0.1
    DB_NAME: iwiki
    DB_USER: root
    DB_PASSWORD: 0000
    DB_HOST: 127.0.0.1
    DB_PORT: 33306
    REDIS_HOST: 127.0.0.1
    REDIS_PORT: 6379
    REDIS_PASSWORD: ""
    REDIS_DB: 0
    DEFAULT_REPO_NAME: default

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 4
            matrix:
                python-version: [ 3.9 ]
        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_DATABASE: iwiki
                    MYSQL_USER: root
                    MYSQL_PASSWORD: 0000
                    MYSQL_ROOT_PASSWORD: 0000
                ports:
                    - 33306:3306
            redis:
                image: redis
                ports:
                    - 6379:6379
        steps:
            -   uses: actions/checkout@v3
            -   name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v3
                with:
                    python-version: ${{ matrix.python-version }}
            -   name: Install Dependencies
                run: |
                    cd backend
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
            -   name: Run Tests
                run: |
                    cd backend
                    python manage.py test
