# Generated by Django 4.0 on 2022-01-03 23:25

from django.db import migrations, models
import modules.conf.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conf",
            fields=[
                (
                    "c_key",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="配置项",
                    ),
                ),
                (
                    "c_type",
                    models.SmallIntegerField(
                        choices=[(1, "布尔"), (2, "字典")], default=1, verbose_name="配置类型"
                    ),
                ),
                (
                    "c_val",
                    models.JSONField(
                        blank=True,
                        default=modules.conf.models.get_default_c_val,
                        null=True,
                        verbose_name="配置内容字典",
                    ),
                ),
                ("c_bool", models.BooleanField(default=True, verbose_name="配置内容布尔")),
            ],
            options={
                "verbose_name": "配置",
                "verbose_name_plural": "配置",
                "db_table": "conf_conf",
            },
        ),
    ]
