# Generated by Django 4.0 on 2022-01-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conf", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conf",
            name="sensitive",
            field=models.BooleanField(default=False, verbose_name="敏感信息"),
        ),
    ]
